# prometheus-values.yaml (개선된 최종 버전)

# ## Alertmanager 설정 (기존과 동일)
alertmanager:
  config:
    global:
      slack_api_url: 'https://hooks.slack.com/services/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'
    route:
      receiver: 'slack-default'
      group_by: ['alertname', 'job']
    receivers:
      - name: 'slack-default'
        slack_configs:
          - channel: '#monitoring-alerts'
            send_resolved: true
            title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for Job: {{ .CommonLabels.job }}'
            text: >-
              {{ range .Alerts }}
              *Alert:* `{{ .Labels.alertname }}`
              *Summary:* {{ .Annotations.summary }}
              *Instance:* `{{ .Labels.instance }}`
              *Severity:* `{{ .Labels.severity }}`
              {{ end }}

# ## node-exporter 권한 문제 해결을 위한 설정
prometheus-node-exporter:
  enabled: true
  securityContext:
    privileged: true

# ## [⭐️ 수정] Prometheus 서버에 경고 규칙을 추가합니다.
serverFiles:
  alerting_rules.yml:
    groups:
      - name: MicroserviceRules
        rules:
          - alert: UserServiceDown
            expr: up{job="user-service"} == 0 or absent(up{job="user-service"})
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "User Service instance is down or missing"
              description: "The job 'user-service' has no running instances."
          # - alert: AIServiceDown
          #   expr: up{job="ai-service"} == 0 or absent(up{job="ai-service"})
          #   for: 1m
          #   labels:
          #     severity: critical
          #   annotations:
          #     summary: "AI Service instance is down or missing"
          #     description: "The job 'ai-service' has no running instances."

# ## [⭐️ 수정] Prometheus가 기본 감시 대상 외에, 우리 서비스를 '추가'로 감시하도록 설정합니다.
extraScrapeConfigs: |
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: user-service
  # - job_name: 'ai-service'
  #   metrics_path: '/actuator/prometheus'
  #   kubernetes_sd_configs:
  #     - role: pod
  #   relabel_configs:
  #     - source_labels: [__meta_kubernetes_pod_label_app]
  #       action: keep
  #       regex: ai-service